# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CICD with Maven 

on:
  push:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.6.8'
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
    - name: Maven Version set
      run: mvn versions:set -DnewVersion=${{ steps.gitversion.outputs.semVer }}
    - name: Build with Maven
      id: maven-build
      run: mvn -B package --file pom.xml
  # cd:
  #   runs-on: ubuntu-latest
  #   needs: [ci]
  #   steps:
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: jmeter-rabbit-amq-${{ steps.gitversion.outputs.semVer }}.jar
        path: target
    # - name: Install GitReleaseManager
    #   uses: gittools/actions/gitreleasemanager/setup@v0.9.2
    #   with:
    #     versionSpec: '0.10.x'
    # - name: Create release with GitReleaseManager
    #   uses: gittools/actions/gitreleasemanager/create@v0.9.2
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     owner: 'verhyppo'
    #     repository: 'someRepository'
    #     milestone: '${{ steps.gitversion.outputs.semVer }}'
    #     name: 'v${{ steps.gitversion.outputs.semVer }}'
    #     assets:  |
    #       target/jmeter-rabbit-amq-${{ steps.gitversion.outputs.semVer }}.jar
